name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: abishek-vk
          outputs: dist/github-contribution-grid-snake.svg
          
      - name: Generate snake-dark.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: abishek-vk
          outputs: dist/github-contribution-grid-snake-dark.svg
          
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
