name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Update stats cache
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/cache_seconds=1800/cache_seconds=1800\&t=$TIMESTAMP/g" README.md
          
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update GitHub stats cache" || exit 0
          git push
